spring:
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: customer-service
              uri: http://localhost:8080
              predicates:
                - Path=/rest-repos/customers/**
            - id: inventory-service
              uri: http://localhost:8081
              predicates:
                - Path=/rest-repos/products/**